import 'package:prescription_management_system/domain/prescription.domain.dart';
import 'package:prescription_management_system/domain/doctor.domain.dart';
import 'package:prescription_management_system/domain/patient.domain.dart';
import 'package:test/test.dart';

void runDoctorTests() {
  group('Doctor:', () {
    var doctorTest = DoctorTests();
    doctorTest.doctorShouldBeAbleToWritePrescription();
    doctorTest.doctorShouldBeAbleToRegisterPatient();
    doctorTest.doctorIdShouldBeAutoGenerated();
    doctorTest.doctorShouldBeAbleToUpdateInfo();
  });
}

class DoctorTests {
  void doctorShouldBeAbleToWritePrescription() {
    test('Doctor Write Prescription', () {
      // INSTANCE
      Doctor doctor = Doctor( name: 'Ronan The Best', username: 'ronanthebest', password: 'ronanamazon' );
      Patient patient = Patient( name: 'Prak Pychey', gender: Gender.male, phoneNumber: '123456789' );

      // METHOD
      Prescription prescription = doctor.writePrescription( patient,
        patientCondition: 'Fever and Headache',
        notes: 'Take With Food',
      );

      // EXPECT
      expect(prescription.doctorId, equals(doctor.id));
      expect(prescription.patientId, equals(patient.id));
      expect(prescription.patientCondition, equals('Fever and Headache'));
      expect(prescription.notes, equals('Take With Food'));
    });
  }

  void doctorShouldBeAbleToRegisterPatient() {
    test('Doctor Register Patient', () {
      // INSTANCE
      Doctor doctor = Doctor( name: 'Ronan The Best', username: 'ronanthebest', password: 'ronanamazon' );

      // METHOD
      Patient patient = doctor.registerPatient(name: 'Prak Pychey', gender: Gender.male, phoneNumber: '123456789' );

      // EXPECT
      expect(patient.name, equals('Prak Pychey'));
      expect(patient.gender, equals(Gender.male));
      expect(patient.phoneNumber, equals('123456789'));
      expect(patient.id, isNotEmpty);
    });
  }

  void doctorIdShouldBeAutoGenerated() {
    test('DoctorID Auto Generated', () {
      // METHOD
      Doctor doctor = Doctor( name: 'Ronan The Best', username: 'ronanthebest', password: 'ronanamazon' );

      // EXPECT
      expect(doctor.id, isNotEmpty);
      expect(doctor.id.length, greaterThan(0));
    });
  }

  void doctorShouldBeAbleToUpdateInfo() {
    test('Doctor Update Info', () {
      // INSTANCE
      Doctor doctor = Doctor( name: 'Ronan The Best', username: 'ronanthebest', password: 'ronanamazon' );

      // METHOD
      doctor.updateInfo( name: 'The Best Ronan', username: 'thebestronan', password: 'amazonronan' );

      // EXPECT
      expect(doctor.name, equals('The Best Ronan'));
      expect(doctor.username, equals('thebestronan'));
      expect(doctor.password, equals('amazonronan'));
    });
  }
}