import 'package:prescription_management_system/domain/medicine.domain.dart';
import 'package:test/test.dart';

void runMedicineTests() {
  group('Medicine:', () {
    var medicineTest = MedicineTests();
    medicineTest.medicineCorrectlyIdentifyExpired();
    medicineTest.medicineStockReduces();
    medicineTest.medicineThrowsExceptionOnInsufficientStock();
    medicineTest.medicineIdAutoGenerated();
  });
}

class MedicineTests {
  void medicineCorrectlyIdentifyExpired() {
    test('Medicine Correctly Identify Expired', () {
      // INSTANCE
      Medicine expiredMedicine = Medicine(
        name: 'SiemReap Expired',
        stockQuantity: 50,
        price: 5.99,
        usage: 'Usage',
        expiryDate: DateTime.now().subtract(Duration(days: 1)),
      );

      Medicine validMedicine = Medicine(
        name: 'SiemReap Valid',
        stockQuantity: 50,
        price: 5.99,
        usage: 'Usage',
        expiryDate: DateTime.now().add(Duration(days: 365)),
      );

      // METHOD & EXPECT
      expect(expiredMedicine.isExpired(), isTrue);
      expect(validMedicine.isExpired(), isFalse);
    });
  }

  void medicineStockReduces() {
    test('Medicine Stock Reduces', () {
      // INSTANCE
      Medicine medicine = Medicine(
        name: 'SiemReap',
        stockQuantity: 100,
        price: 5.99,
        usage: 'Heal Who Hurt',
        expiryDate: DateTime.now().add(Duration(days: 365)),
      );

      // METHOD
      medicine.reduceStock(10);

      // EXPECT
      expect(medicine.stockQuantity, equals(90));
    });
  }

  void medicineThrowsExceptionOnInsufficientStock() {
    test('Medicine Throws Exception On Insufficient Stock', () {
      // INSTANCE
      Medicine medicine = Medicine(
        name: 'SiemReap',
        stockQuantity: 5,
        price: 5.99,
        usage: 'Heal Who Hurt',
        expiryDate: DateTime.now().add(Duration(days: 365)),
      );

      // EXPECT
      expect(
        () => medicine.reduceStock(10),
        throwsA(isA<Exception>()),
      );
    });
  }

  void medicineIdAutoGenerated() {
    test('Medicine ID Auto Generated', () {
      // METHOD
      Medicine medicine = Medicine(
        name: 'SiemReap',
        stockQuantity: 100,
        price: 5.99,
        usage: 'Usage',
        expiryDate: DateTime.now().add(Duration(days: 365)),
      );

      // EXPECT
      expect(medicine.id, isNotEmpty);
      expect(medicine.id.length, greaterThan(0));
    });
  }
}