import 'package:prescription_management_system/domain/patient.domain.dart';
import 'package:test/test.dart';

void runPatientTests() {
  group('Patient:', () {
    var patientTest = PatientTests();
    patientTest.patientCreatedWithCorrectGender();
    patientTest.patientIdAutoGenerated();
  });
}

class PatientTests {
  void patientCreatedWithCorrectGender() {
    test('Patient Created With Correct Gender', () {
      // INSTANCE
      Patient malePatient = Patient(
        name: 'Patient Pychey',
        gender: Gender.male,
        phoneNumber: '123456789',
      );

      Patient femalePatient = Patient(
        name: 'Vong Rithea',
        gender: Gender.female,
        phoneNumber: '987654321',
      );

      // EXPECT
      expect(malePatient.gender, equals(Gender.male));
      expect(femalePatient.gender, equals(Gender.female));
    });
  }

  void patientIdAutoGenerated() {
    test('Patient ID Auto Generated', () {
      // METHOD
      Patient patient = Patient(
        name: 'Patient Pychey',
        gender: Gender.male,
        phoneNumber: '123456789',
      );

      // EXPECT
      expect(patient.id, isNotEmpty);
      expect(patient.id.length, greaterThan(0));
    });
  }
}